import CryptoKit
import Foundation

// The Automix model download, end to end, against a local fixture server.
//
// What the app does here is not "fetch a file": it is fetch, resume, verify, refuse,
// install, and remove — and every one of those is invisible from the outside. A bad
// resume that silently restarts a 113 MB transfer, or a checksum check that passes a
// truncated graph, would look exactly like a working download in the shipped app.
//
// Run: scripts/check-models.sh
// Set MODELS_LIVE=1 to also download the real pinned beat model and check its
// SHA-256, which is how manifest drift against Hugging Face gets caught.

let environment = ProcessInfo.processInfo.environment
guard let base = environment["MODELS_FIXTURE"], let baseURL = URL(string: base) else {
    FileHandle.standardError.write(Data("MODELS_FIXTURE is not set\n".utf8))
    exit(2)
}

var failures: [String] = []

func check(_ name: String, _ condition: Bool, _ detail: String = "") {
    if condition {
        print("  ok    \(name)")
    } else {
        print("  FAIL  \(name)\(detail.isEmpty ? "" : " — \(detail)")")
        failures.append(name)
    }
}

func sha256(of url: URL) -> String {
    guard let handle = try? FileHandle(forReadingFrom: url) else { return "" }
    defer { try? handle.close() }
    var hasher = SHA256()
    while let chunk = try? handle.read(upToCount: 1 << 20), !chunk.isEmpty {
        hasher.update(data: chunk)
    }
    return hasher.finalize().map { String(format: "%02x", $0) }.joined()
}

struct Fixture {
    let size: Int64
    let goodSHA: String
}

func temporaryDirectory(_ name: String) -> URL {
    let url = FileManager.default.temporaryDirectory
        .appendingPathComponent("bitchord-models-\(name)-\(UUID().uuidString)", isDirectory: true)
    try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
    return url
}

func spec(
    _ id: AutomixModelStore.ModelID,
    path: String,
    name: String,
    sha: String,
    size: Int64
) -> AutomixModelStore.ModelSpec {
    AutomixModelStore.ModelSpec(
        id: id,
        fileName: name,
        displayName: "fixture",
        detail: "",
        byteCount: size,
        sha256: sha,
        url: baseURL.appendingPathComponent(path)
    )
}

/// The fixture files are generated by the server; the harness hashes the same bytes
/// it asked the server to serve, so size and digest are facts rather than constants.
func readFixture() -> Fixture {
    let url = URL(fileURLWithPath: environment["MODELS_FIXTURE_DIR"] ?? ".").appendingPathComponent("good.bin")
    let attributes = try? FileManager.default.attributesOfItem(atPath: url.path)
    let size = (attributes?[.size] as? NSNumber)?.int64Value ?? 0
    return Fixture(size: size, goodSHA: sha256(of: url))
}

func requestCount() async -> Int {
    guard let (data, _) = try? await URLSession.shared.data(from: baseURL.appendingPathComponent("count")),
          let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else { return -1 }
    return (object["requests"] as? Int) ?? -1
}

let fixture = readFixture()
guard fixture.size > 0, !fixture.goodSHA.isEmpty else {
    FileHandle.standardError.write(Data("the fixture server did not produce good.bin\n".utf8))
    exit(2)
}
print("fixture: \(fixture.size) bytes, sha256 \(fixture.goodSHA.prefix(12))…")

// MARK: - 1. A good download installs, records, and can be removed

print("\ngood download")
do {
    let directory = temporaryDirectory("good")
    let store = AutomixModelStore(
        directory: directory,
        specs: [spec(.beat, path: "good.bin", name: "beat.fixture", sha: fixture.goodSHA, size: fixture.size)]
    )
    await store.download(.beat, allowMetered: true)

    check("status is installed", store.status(of: .beat).isInstalled, "\(store.status(of: .beat))")
    check("path is reported", store.installedPath(.beat) != nil)
    check("no part file is left", !FileManager.default.fileExists(atPath: directory.appendingPathComponent("beat.fixture.part").path))
    check("sidecar written", FileManager.default.fileExists(atPath: directory.appendingPathComponent("installed.json").path))
    check("bytes counted", store.totalBytesOnDisk == fixture.size, "\(store.totalBytesOnDisk)")

    // A second download must be a no-op, not a re-fetch.
    let before = await requestCount()
    await store.download(.beat, allowMetered: true)
    let after = await requestCount()
    check("installed model is not fetched again", before == after)

    store.remove(.beat)
    check("remove leaves notInstalled", store.status(of: .beat) == .notInstalled)
    check("remove deletes the file", store.installedPath(.beat) == nil)
}

// MARK: - 2. The right length with the wrong bytes is refused

print("\nchecksum mismatch")
do {
    let directory = temporaryDirectory("corrupt")
    let store = AutomixModelStore(
        directory: directory,
        specs: [spec(.beat, path: "corrupt.bin", name: "beat.fixture", sha: fixture.goodSHA, size: fixture.size)]
    )
    await store.download(.beat, allowMetered: true)

    if case .failed(let message) = store.status(of: .beat) {
        check("status is failed", true)
        check("message names the checksum", message.localizedCaseInsensitiveContains("checksum"), message)
    } else {
        check("status is failed", false, "\(store.status(of: .beat))")
    }
    check("nothing installed", store.installedPath(.beat) == nil)
    check("bad part removed", !FileManager.default.fileExists(atPath: directory.appendingPathComponent("beat.fixture.part").path))
}

// MARK: - 3. An interrupted transfer resumes rather than restarting

print("\ninterrupted transfer")
do {
    let directory = temporaryDirectory("resume")
    let store = AutomixModelStore(
        directory: directory,
        specs: [spec(.beat, path: "cut.bin", name: "beat.fixture", sha: fixture.goodSHA, size: fixture.size)]
    )
    let part = directory.appendingPathComponent("beat.fixture.part")

    await store.download(.beat, allowMetered: true)
    let partial = (try? FileManager.default.attributesOfItem(atPath: part.path))?[.size] as? NSNumber
    let partialBytes = partial?.int64Value ?? 0

    check("first attempt does not install", store.installedPath(.beat) == nil)
    check("partial bytes are kept", partialBytes > 0 && partialBytes < fixture.size, "kept \(partialBytes) of \(fixture.size)")
    check("failure mentions the kept bytes", {
        if case .failed(let message) = store.status(of: .beat) { return message.contains("resume") }
        return false
    }())

    await store.download(.beat, allowMetered: true)
    check("retry installs", store.status(of: .beat).isInstalled, "\(store.status(of: .beat))")
    if let path = store.installedPath(.beat) {
        check("installed bytes match the source", sha256(of: URL(fileURLWithPath: path)) == fixture.goodSHA)
    }
}

// MARK: - 4. A metered connection with Wi-Fi-only on never opens a connection

print("\nmetered gate")
do {
    let directory = temporaryDirectory("metered")
    let store = AutomixModelStore(
        directory: directory,
        specs: [spec(.beat, path: "good.bin", name: "beat.fixture", sha: fixture.goodSHA, size: fixture.size)]
    )
    let before = await requestCount()
    await store.download(.beat, allowMetered: false)
    let after = await requestCount()

    check("status is blockedByWifi", store.status(of: .beat) == .blockedByWifi, "\(store.status(of: .beat))")
    check("nothing was requested", before == after, "\(before) → \(after)")

    // The override the row offers.
    await store.download(.beat, allowMetered: true)
    check("override downloads", store.status(of: .beat).isInstalled)
}

// MARK: - 5. Verify catches a file that rotted after install

print("\nverify")
do {
    let directory = temporaryDirectory("verify")
    let store = AutomixModelStore(
        directory: directory,
        specs: [spec(.beat, path: "good.bin", name: "beat.fixture", sha: fixture.goodSHA, size: fixture.size)]
    )
    await store.download(.beat, allowMetered: true)
    check("installed first", store.status(of: .beat).isInstalled)

    guard let path = store.installedPath(.beat) else { exit(1) }
    let file = URL(fileURLWithPath: path)
    var bytes = try Data(contentsOf: file)
    bytes[0] ^= 0xFF
    try Data(bytes).write(to: file)

    let survived = store.verify(.beat)
    check("verify rejects the file", !survived)
    check("rejected file is removed", store.installedPath(.beat) == nil)
    if case .failed = store.status(of: .beat) { check("status explains it", true) } else {
        check("status explains it", false, "\(store.status(of: .beat))")
    }
}

// MARK: - 6. Optional: the pinned graph itself

if environment["MODELS_LIVE"] == "1" {
    print("\nlive beat model")
    let directory = temporaryDirectory("live")
    let store = AutomixModelStore(directory: directory)
    await store.download(.beat, allowMetered: true)
    check("pinned beat model downloads", store.status(of: .beat).isInstalled, "\(store.status(of: .beat))")
    if let path = store.installedPath(.beat) {
        check("pinned beat model hashes correctly", sha256(of: URL(fileURLWithPath: path)) == store.spec(.beat).sha256)
    }
}

print("")
if failures.isEmpty {
    print("models: all checks passed")
    exit(0)
} else {
    print("models: \(failures.count) check(s) failed: \(failures.joined(separator: ", "))")
    exit(1)
}
